<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CfSharp\CfSharp.csproj" />
    <ProjectReference Include="..\..\src\CfSharp.Native\CfSharp.Native.csproj" />
    <ProjectReference Include="..\..\src\CfSharp.Storage.Sqlite\CfSharp.Storage.Sqlite.csproj" />
    <ProjectReference Include="..\CfSharp.Storage.Sqlite.CrashHarness\CfSharp.Storage.Sqlite.CrashHarness.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
