#include <windows.h>
#include <winioctl.h>
#include <winternl.h>
#include <cfapi.h>

#include <cstddef>
#include <iostream>

int main()
{
    constexpr CF_CALLBACK_REGISTRATION callbackRegistrationEnd = CF_CALLBACK_REGISTRATION_END;

    // The probe emits machine-readable ABI facts obtained from the active
    // Windows SDK. Managed tests will compare these values with the bindings.
    std::cout << "{\n"
              << "  \"pointerSize\": " << sizeof(void*) << ",\n"
              << "  \"overlappedSize\": " << sizeof(OVERLAPPED) << ",\n"
              << "  \"overlappedOffsetOffset\": " << offsetof(OVERLAPPED, Offset) << ",\n"
              << "  \"overlappedEventOffset\": " << offsetof(OVERLAPPED, hEvent) << ",\n"
              << "  \"fileIdInfoSize\": " << sizeof(FILE_ID_INFO) << ",\n"
              << "  \"fileIdInfoIdOffset\": " << offsetof(FILE_ID_INFO, FileId) << ",\n"
              << "  \"fileStandardInfoSize\": " << sizeof(FILE_STANDARD_INFO) << ",\n"
              << "  \"fileStandardInfoLengthOffset\": " << offsetof(FILE_STANDARD_INFO, EndOfFile) << ",\n"
              << "  \"fileStandardInfoLinksOffset\": " << offsetof(FILE_STANDARD_INFO, NumberOfLinks) << ",\n"
              << "  \"fileStandardInfoDeleteOffset\": " << offsetof(FILE_STANDARD_INFO, DeletePending) << ",\n"
              << "  \"fileStandardInfoDirectoryOffset\": " << offsetof(FILE_STANDARD_INFO, Directory) << ",\n"
              << "  \"fileAttributeTagInfoSize\": " << sizeof(FILE_ATTRIBUTE_TAG_INFO) << ",\n"
              << "  \"readFileUsnDataControlCode\": " << FSCTL_READ_FILE_USN_DATA << ",\n"
              << "  \"readFileUsnDataSize\": " << sizeof(READ_FILE_USN_DATA) << ",\n"
              << "  \"readFileUsnDataMaxMajorVersionOffset\": " << offsetof(READ_FILE_USN_DATA, MaxMajorVersion) << ",\n"
              << "  \"usnRecordV2UsnOffset\": " << offsetof(USN_RECORD_V2, Usn) << ",\n"
              << "  \"usnRecordV3UsnOffset\": " << offsetof(USN_RECORD_V3, Usn) << ",\n"
              << "  \"usnRecordV2HeaderLength\": " << offsetof(USN_RECORD_V2, FileName) << ",\n"
              << "  \"usnRecordV3HeaderLength\": " << offsetof(USN_RECORD_V3, FileName) << ",\n"
              << "  \"cfEndOfFile\": " << CF_EOF << ",\n"
              << "  \"cfDefaultRequestKey\": " << CF_REQUEST_KEY_DEFAULT << ",\n"
              << "  \"cfMaxFileIdentityLength\": " << CF_PLACEHOLDER_MAX_FILE_IDENTITY_LENGTH << ",\n"
              << "  \"cfMaxPriorityHint\": " << CF_MAX_PRIORITY_HINT << ",\n"
              << "  \"cfMaxProviderNameLength\": " << CF_MAX_PROVIDER_NAME_LENGTH << ",\n"
              << "  \"cfMaxProviderVersionLength\": " << CF_MAX_PROVIDER_VERSION_LENGTH << ",\n"
              << "  \"cfCallbackRegistrationEndType\": " << callbackRegistrationEnd.Type << ",\n"
              << "  \"cfCallbackRegistrationEndCallbackNull\": " << (callbackRegistrationEnd.Callback == nullptr) << ",\n"
              << "  \"cfPlatformInfoSize\": " << sizeof(CF_PLATFORM_INFO) << ",\n"
              << "  \"cfPlatformInfoBuildNumberOffset\": " << offsetof(CF_PLATFORM_INFO, BuildNumber) << ",\n"
              << "  \"cfPlatformInfoRevisionNumberOffset\": " << offsetof(CF_PLATFORM_INFO, RevisionNumber) << ",\n"
              << "  \"cfPlatformInfoIntegrationNumberOffset\": " << offsetof(CF_PLATFORM_INFO, IntegrationNumber) << ",\n"
              << "  \"cfHydrationPolicySize\": " << sizeof(CF_HYDRATION_POLICY) << ",\n"
              << "  \"cfPopulationPolicySize\": " << sizeof(CF_POPULATION_POLICY) << ",\n"
              << "  \"cfSyncPoliciesSize\": " << sizeof(CF_SYNC_POLICIES) << ",\n"
              << "  \"cfSyncPoliciesHydrationOffset\": " << offsetof(CF_SYNC_POLICIES, Hydration) << ",\n"
              << "  \"cfSyncPoliciesPopulationOffset\": " << offsetof(CF_SYNC_POLICIES, Population) << ",\n"
              << "  \"cfSyncPoliciesInSyncOffset\": " << offsetof(CF_SYNC_POLICIES, InSync) << ",\n"
              << "  \"cfSyncPoliciesHardLinkOffset\": " << offsetof(CF_SYNC_POLICIES, HardLink) << ",\n"
              << "  \"cfSyncPoliciesPlaceholderManagementOffset\": " << offsetof(CF_SYNC_POLICIES, PlaceholderManagement) << ",\n"
              << "  \"cfSyncRegistrationSize\": " << sizeof(CF_SYNC_REGISTRATION) << ",\n"
              << "  \"cfSyncRegistrationProviderNameOffset\": " << offsetof(CF_SYNC_REGISTRATION, ProviderName) << ",\n"
              << "  \"cfSyncRegistrationProviderVersionOffset\": " << offsetof(CF_SYNC_REGISTRATION, ProviderVersion) << ",\n"
              << "  \"cfSyncRegistrationSyncRootIdentityOffset\": " << offsetof(CF_SYNC_REGISTRATION, SyncRootIdentity) << ",\n"
              << "  \"cfSyncRegistrationSyncRootIdentityLengthOffset\": " << offsetof(CF_SYNC_REGISTRATION, SyncRootIdentityLength) << ",\n"
              << "  \"cfSyncRegistrationFileIdentityOffset\": " << offsetof(CF_SYNC_REGISTRATION, FileIdentity) << ",\n"
              << "  \"cfSyncRegistrationFileIdentityLengthOffset\": " << offsetof(CF_SYNC_REGISTRATION, FileIdentityLength) << ",\n"
              << "  \"cfSyncRegistrationProviderIdOffset\": " << offsetof(CF_SYNC_REGISTRATION, ProviderId) << ",\n"
              << "  \"cfSyncRootBasicInfoSize\": " << sizeof(CF_SYNC_ROOT_BASIC_INFO) << ",\n"
              << "  \"cfSyncRootProviderInfoSize\": " << sizeof(CF_SYNC_ROOT_PROVIDER_INFO) << ",\n"
              << "  \"cfSyncRootProviderInfoProviderNameOffset\": " << offsetof(CF_SYNC_ROOT_PROVIDER_INFO, ProviderName) << ",\n"
              << "  \"cfSyncRootProviderInfoProviderVersionOffset\": " << offsetof(CF_SYNC_ROOT_PROVIDER_INFO, ProviderVersion) << ",\n"
              << "  \"cfSyncRootStandardInfoSize\": " << sizeof(CF_SYNC_ROOT_STANDARD_INFO) << ",\n"
              << "  \"cfSyncRootStandardInfoProviderNameOffset\": " << offsetof(CF_SYNC_ROOT_STANDARD_INFO, ProviderName) << ",\n"
              << "  \"cfSyncRootStandardInfoProviderVersionOffset\": " << offsetof(CF_SYNC_ROOT_STANDARD_INFO, ProviderVersion) << ",\n"
              << "  \"cfSyncRootStandardInfoIdentityLengthOffset\": " << offsetof(CF_SYNC_ROOT_STANDARD_INFO, SyncRootIdentityLength) << ",\n"
              << "  \"cfSyncRootStandardInfoIdentityOffset\": " << offsetof(CF_SYNC_ROOT_STANDARD_INFO, SyncRootIdentity) << ",\n"
              << "  \"cfRegisterFlagMarkInSyncOnRoot\": " << CF_REGISTER_FLAG_MARK_IN_SYNC_ON_ROOT << ",\n"
              << "  \"cfHydrationModifierAllowFullRestart\": " << CF_HYDRATION_POLICY_MODIFIER_ALLOW_FULL_RESTART_HYDRATION << ",\n"
              << "  \"cfInSyncPolicyTrackAll\": " << CF_INSYNC_POLICY_TRACK_ALL << ",\n"
              << "  \"cfSyncRootInfoProvider\": " << CF_SYNC_ROOT_INFO_PROVIDER << ",\n"
              << "  \"cfConnectionKeySize\": " << sizeof(CF_CONNECTION_KEY) << ",\n"
              << "  \"cfTransferKeySize\": " << sizeof(CF_TRANSFER_KEY) << ",\n"
              << "  \"cfRequestKeySize\": " << sizeof(CF_REQUEST_KEY) << ",\n"
              << "  \"cfSyncStatusSize\": " << sizeof(CF_SYNC_STATUS) << ",\n"
              << "  \"cfSyncStatusCodeOffset\": " << offsetof(CF_SYNC_STATUS, Code) << ",\n"
              << "  \"cfSyncStatusDescriptionOffsetOffset\": " << offsetof(CF_SYNC_STATUS, DescriptionOffset) << ",\n"
              << "  \"cfSyncStatusDeviceIdOffsetOffset\": " << offsetof(CF_SYNC_STATUS, DeviceIdOffset) << ",\n"
              << "  \"cfProcessInfoSize\": " << sizeof(CF_PROCESS_INFO) << ",\n"
              << "  \"cfCallbackInfoSize\": " << sizeof(CF_CALLBACK_INFO) << ",\n"
              << "  \"cfCallbackInfoConnectionKeyOffset\": " << offsetof(CF_CALLBACK_INFO, ConnectionKey) << ",\n"
              << "  \"cfCallbackInfoCallbackContextOffset\": " << offsetof(CF_CALLBACK_INFO, CallbackContext) << ",\n"
              << "  \"cfCallbackInfoNormalizedPathOffset\": " << offsetof(CF_CALLBACK_INFO, NormalizedPath) << ",\n"
              << "  \"cfCallbackInfoTransferKeyOffset\": " << offsetof(CF_CALLBACK_INFO, TransferKey) << ",\n"
              << "  \"cfCallbackInfoPriorityHintOffset\": " << offsetof(CF_CALLBACK_INFO, PriorityHint) << ",\n"
              << "  \"cfCallbackInfoRequestKeyOffset\": " << offsetof(CF_CALLBACK_INFO, RequestKey) << ",\n"
              << "  \"cfCallbackParametersSize\": " << sizeof(CF_CALLBACK_PARAMETERS) << ",\n"
              << "  \"cfCallbackParametersUnionOffset\": " << offsetof(CF_CALLBACK_PARAMETERS, FetchData) << ",\n"
              << "  \"cfCallbackFetchDataSize\": " << sizeof(((CF_CALLBACK_PARAMETERS*)0)->FetchData) << ",\n"
              << "  \"cfCallbackRegistrationSize\": " << sizeof(CF_CALLBACK_REGISTRATION) << ",\n"
              << "  \"cfCallbackRegistrationCallbackOffset\": " << offsetof(CF_CALLBACK_REGISTRATION, Callback) << ",\n"
              << "  \"cfCallbackTypeNone\": " << CF_CALLBACK_TYPE_NONE << ",\n"
              << "  \"cfConnectFlagBlockSelfImplicitHydration\": " << CF_CONNECT_FLAG_BLOCK_SELF_IMPLICIT_HYDRATION << ",\n"
              << "  \"cfOperationInfoSize\": " << sizeof(CF_OPERATION_INFO) << ",\n"
              << "  \"cfOperationInfoTransferKeyOffset\": " << offsetof(CF_OPERATION_INFO, TransferKey) << ",\n"
              << "  \"cfOperationInfoRequestKeyOffset\": " << offsetof(CF_OPERATION_INFO, RequestKey) << ",\n"
              << "  \"cfOperationParametersSize\": " << sizeof(CF_OPERATION_PARAMETERS) << ",\n"
              << "  \"cfOperationParametersUnionOffset\": " << offsetof(CF_OPERATION_PARAMETERS, TransferData) << ",\n"
              << "  \"cfOperationTransferDataSize\": " << sizeof(((CF_OPERATION_PARAMETERS*)0)->TransferData) << ",\n"
              << "  \"cfFsMetadataSize\": " << sizeof(CF_FS_METADATA) << ",\n"
              << "  \"cfPlaceholderCreateInfoSize\": " << sizeof(CF_PLACEHOLDER_CREATE_INFO) << ",\n"
              << "  \"cfPlaceholderCreateInfoMetadataOffset\": " << offsetof(CF_PLACEHOLDER_CREATE_INFO, FsMetadata) << ",\n"
              << "  \"cfPlaceholderCreateInfoCreateUsnOffset\": " << offsetof(CF_PLACEHOLDER_CREATE_INFO, CreateUsn) << ",\n"
              << "  \"cfPlaceholderCreateFlagAlwaysFull\": " << CF_PLACEHOLDER_CREATE_FLAG_ALWAYS_FULL << ",\n"
              << "  \"cfFileRangeSize\": " << sizeof(CF_FILE_RANGE) << ",\n"
              << "  \"cfFileRangeStartingOffsetOffset\": " << offsetof(CF_FILE_RANGE, StartingOffset) << ",\n"
              << "  \"cfFileRangeLengthOffset\": " << offsetof(CF_FILE_RANGE, Length) << ",\n"
              << "  \"cfConvertFlagForceConvertToCloudFile\": " << CF_CONVERT_FLAG_FORCE_CONVERT_TO_CLOUD_FILE << ",\n"
              << "  \"cfUpdateFlagAllowPartial\": " << CF_UPDATE_FLAG_ALLOW_PARTIAL << ",\n"
              << "  \"cfDehydrateFlagBackground\": " << CF_DEHYDRATE_FLAG_BACKGROUND << ",\n"
              << "  \"cfPinStateInherit\": " << CF_PIN_STATE_INHERIT << ",\n"
              << "  \"cfSetPinFlagRecurseStopOnError\": " << CF_SET_PIN_FLAG_RECURSE_STOP_ON_ERROR << ",\n"
              << "  \"cfInSyncStateInSync\": " << CF_IN_SYNC_STATE_IN_SYNC << ",\n"
              << "  \"cfPlaceholderBasicInfoSize\": " << sizeof(CF_PLACEHOLDER_BASIC_INFO) << ",\n"
              << "  \"cfPlaceholderBasicInfoIdentityOffset\": " << offsetof(CF_PLACEHOLDER_BASIC_INFO, FileIdentity) << ",\n"
              << "  \"cfPlaceholderStandardInfoSize\": " << sizeof(CF_PLACEHOLDER_STANDARD_INFO) << ",\n"
              << "  \"cfPlaceholderStandardInfoIdentityOffset\": " << offsetof(CF_PLACEHOLDER_STANDARD_INFO, FileIdentity) << ",\n"
              << "  \"cfCorrelationVectorSize\": " << sizeof(CORRELATION_VECTOR) << ",\n"
              << "  \"cfCorrelationVectorValueOffset\": " << offsetof(CORRELATION_VECTOR, Vector) << ",\n"
              << "  \"win32FindDataWSize\": " << sizeof(WIN32_FIND_DATAW) << ",\n"
              << "  \"win32FindDataWReparseTagOffset\": " << offsetof(WIN32_FIND_DATAW, dwReserved0) << ",\n"
              << "  \"win32FindDataWFileNameOffset\": " << offsetof(WIN32_FIND_DATAW, cFileName) << ",\n"
              << "  \"cfPlaceholderInfoClassStandard\": " << CF_PLACEHOLDER_INFO_STANDARD << ",\n"
              << "  \"cfPlaceholderRangeInfoModified\": " << CF_PLACEHOLDER_RANGE_INFO_MODIFIED << ",\n"
              << "  \"cfPlaceholderStatePartiallyOnDisk\": " << CF_PLACEHOLDER_STATE_PARTIALLY_ON_DISK << ",\n"
              << "  \"enumValues\": {\n"
              << "    \"CF_CALLBACK_CANCEL_FLAGS\": [" << CF_CALLBACK_CANCEL_FLAG_NONE << ", " << CF_CALLBACK_CANCEL_FLAG_IO_TIMEOUT << ", " << CF_CALLBACK_CANCEL_FLAG_IO_ABORTED << "],\n"
              << "    \"CF_CALLBACK_CLOSE_COMPLETION_FLAGS\": [" << CF_CALLBACK_CLOSE_COMPLETION_FLAG_NONE << ", " << CF_CALLBACK_CLOSE_COMPLETION_FLAG_DELETED << "],\n"
              << "    \"CF_CALLBACK_DEHYDRATE_COMPLETION_FLAGS\": [" << CF_CALLBACK_DEHYDRATE_COMPLETION_FLAG_NONE << ", " << CF_CALLBACK_DEHYDRATE_COMPLETION_FLAG_BACKGROUND << ", " << CF_CALLBACK_DEHYDRATE_COMPLETION_FLAG_DEHYDRATED << "],\n"
              << "    \"CF_CALLBACK_DEHYDRATE_FLAGS\": [" << CF_CALLBACK_DEHYDRATE_FLAG_NONE << ", " << CF_CALLBACK_DEHYDRATE_FLAG_BACKGROUND << "],\n"
              << "    \"CF_CALLBACK_DEHYDRATION_REASON\": [" << CF_CALLBACK_DEHYDRATION_REASON_NONE << ", " << CF_CALLBACK_DEHYDRATION_REASON_USER_MANUAL << ", " << CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_LOW_SPACE << ", " << CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_INACTIVITY << ", " << CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_OS_UPGRADE << "],\n"
              << "    \"CF_CALLBACK_DELETE_COMPLETION_FLAGS\": [" << CF_CALLBACK_DELETE_COMPLETION_FLAG_NONE << "],\n"
              << "    \"CF_CALLBACK_DELETE_FLAGS\": [" << CF_CALLBACK_DELETE_FLAG_NONE << ", " << CF_CALLBACK_DELETE_FLAG_IS_DIRECTORY << ", " << CF_CALLBACK_DELETE_FLAG_IS_UNDELETE << "],\n"
              << "    \"CF_CALLBACK_FETCH_DATA_FLAGS\": [" << CF_CALLBACK_FETCH_DATA_FLAG_NONE << ", " << CF_CALLBACK_FETCH_DATA_FLAG_RECOVERY << ", " << CF_CALLBACK_FETCH_DATA_FLAG_EXPLICIT_HYDRATION << "],\n"
              << "    \"CF_CALLBACK_FETCH_PLACEHOLDERS_FLAGS\": [" << CF_CALLBACK_FETCH_PLACEHOLDERS_FLAG_NONE << "],\n"
              << "    \"CF_CALLBACK_OPEN_COMPLETION_FLAGS\": [" << CF_CALLBACK_OPEN_COMPLETION_FLAG_NONE << ", " << CF_CALLBACK_OPEN_COMPLETION_FLAG_PLACEHOLDER_UNKNOWN << ", " << CF_CALLBACK_OPEN_COMPLETION_FLAG_PLACEHOLDER_UNSUPPORTED << "],\n"
              << "    \"CF_CALLBACK_RENAME_COMPLETION_FLAGS\": [" << CF_CALLBACK_RENAME_COMPLETION_FLAG_NONE << "],\n"
              << "    \"CF_CALLBACK_RENAME_FLAGS\": [" << CF_CALLBACK_RENAME_FLAG_NONE << ", " << CF_CALLBACK_RENAME_FLAG_IS_DIRECTORY << ", " << CF_CALLBACK_RENAME_FLAG_SOURCE_IN_SCOPE << ", " << CF_CALLBACK_RENAME_FLAG_TARGET_IN_SCOPE << "],\n"
              << "    \"CF_CALLBACK_TYPE\": [" << CF_CALLBACK_TYPE_FETCH_DATA << ", " << CF_CALLBACK_TYPE_VALIDATE_DATA << ", " << CF_CALLBACK_TYPE_CANCEL_FETCH_DATA << ", " << CF_CALLBACK_TYPE_FETCH_PLACEHOLDERS << ", " << CF_CALLBACK_TYPE_CANCEL_FETCH_PLACEHOLDERS << ", " << CF_CALLBACK_TYPE_NOTIFY_FILE_OPEN_COMPLETION << ", " << CF_CALLBACK_TYPE_NOTIFY_FILE_CLOSE_COMPLETION << ", " << CF_CALLBACK_TYPE_NOTIFY_DEHYDRATE << ", " << CF_CALLBACK_TYPE_NOTIFY_DEHYDRATE_COMPLETION << ", " << CF_CALLBACK_TYPE_NOTIFY_DELETE << ", " << CF_CALLBACK_TYPE_NOTIFY_DELETE_COMPLETION << ", " << CF_CALLBACK_TYPE_NOTIFY_RENAME << ", " << CF_CALLBACK_TYPE_NOTIFY_RENAME_COMPLETION << ", " << CF_CALLBACK_TYPE_NONE << "],\n"
              << "    \"CF_CALLBACK_VALIDATE_DATA_FLAGS\": [" << CF_CALLBACK_VALIDATE_DATA_FLAG_NONE << ", " << CF_CALLBACK_VALIDATE_DATA_FLAG_EXPLICIT_HYDRATION << "],\n"
              << "    \"CF_CONNECT_FLAGS\": [" << CF_CONNECT_FLAG_NONE << ", " << CF_CONNECT_FLAG_REQUIRE_PROCESS_INFO << ", " << CF_CONNECT_FLAG_REQUIRE_FULL_FILE_PATH << ", " << CF_CONNECT_FLAG_BLOCK_SELF_IMPLICIT_HYDRATION << "],\n"
              << "    \"CF_CONVERT_FLAGS\": [" << CF_CONVERT_FLAG_NONE << ", " << CF_CONVERT_FLAG_MARK_IN_SYNC << ", " << CF_CONVERT_FLAG_DEHYDRATE << ", " << CF_CONVERT_FLAG_ENABLE_ON_DEMAND_POPULATION << ", " << CF_CONVERT_FLAG_ALWAYS_FULL << ", " << CF_CONVERT_FLAG_FORCE_CONVERT_TO_CLOUD_FILE << "],\n"
              << "    \"CF_CREATE_FLAGS\": [" << CF_CREATE_FLAG_NONE << ", " << CF_CREATE_FLAG_STOP_ON_ERROR << "],\n"
              << "    \"CF_DEHYDRATE_FLAGS\": [" << CF_DEHYDRATE_FLAG_NONE << ", " << CF_DEHYDRATE_FLAG_BACKGROUND << "],\n"
              << "    \"CF_HARDLINK_POLICY\": [" << CF_HARDLINK_POLICY_NONE << ", " << CF_HARDLINK_POLICY_ALLOWED << "],\n"
              << "    \"CF_HYDRATE_FLAGS\": [" << CF_HYDRATE_FLAG_NONE << "],\n"
              << "    \"CF_HYDRATION_POLICY_MODIFIER\": [" << CF_HYDRATION_POLICY_MODIFIER_NONE << ", " << CF_HYDRATION_POLICY_MODIFIER_VALIDATION_REQUIRED << ", " << CF_HYDRATION_POLICY_MODIFIER_STREAMING_ALLOWED << ", " << CF_HYDRATION_POLICY_MODIFIER_AUTO_DEHYDRATION_ALLOWED << ", " << CF_HYDRATION_POLICY_MODIFIER_ALLOW_FULL_RESTART_HYDRATION << "],\n"
              << "    \"CF_HYDRATION_POLICY_PRIMARY\": [" << CF_HYDRATION_POLICY_PARTIAL << ", " << CF_HYDRATION_POLICY_PROGRESSIVE << ", " << CF_HYDRATION_POLICY_FULL << ", " << CF_HYDRATION_POLICY_ALWAYS_FULL << "],\n"
              << "    \"CF_IN_SYNC_STATE\": [" << CF_IN_SYNC_STATE_NOT_IN_SYNC << ", " << CF_IN_SYNC_STATE_IN_SYNC << "],\n"
              << "    \"CF_INSYNC_POLICY\": [" << CF_INSYNC_POLICY_NONE << ", " << CF_INSYNC_POLICY_TRACK_FILE_CREATION_TIME << ", " << CF_INSYNC_POLICY_TRACK_FILE_READONLY_ATTRIBUTE << ", " << CF_INSYNC_POLICY_TRACK_FILE_HIDDEN_ATTRIBUTE << ", " << CF_INSYNC_POLICY_TRACK_FILE_SYSTEM_ATTRIBUTE << ", " << CF_INSYNC_POLICY_TRACK_DIRECTORY_CREATION_TIME << ", " << CF_INSYNC_POLICY_TRACK_DIRECTORY_READONLY_ATTRIBUTE << ", " << CF_INSYNC_POLICY_TRACK_DIRECTORY_HIDDEN_ATTRIBUTE << ", " << CF_INSYNC_POLICY_TRACK_DIRECTORY_SYSTEM_ATTRIBUTE << ", " << CF_INSYNC_POLICY_TRACK_FILE_LAST_WRITE_TIME << ", " << CF_INSYNC_POLICY_TRACK_DIRECTORY_LAST_WRITE_TIME << ", " << CF_INSYNC_POLICY_TRACK_FILE_ALL << ", " << CF_INSYNC_POLICY_TRACK_DIRECTORY_ALL << ", " << CF_INSYNC_POLICY_TRACK_ALL << ", " << CF_INSYNC_POLICY_PRESERVE_INSYNC_FOR_SYNC_ENGINE << "],\n"
              << "    \"CF_OPEN_FILE_FLAGS\": [" << CF_OPEN_FILE_FLAG_NONE << ", " << CF_OPEN_FILE_FLAG_EXCLUSIVE << ", " << CF_OPEN_FILE_FLAG_WRITE_ACCESS << ", " << CF_OPEN_FILE_FLAG_DELETE_ACCESS << ", " << CF_OPEN_FILE_FLAG_FOREGROUND << "],\n"
              << "    \"CF_OPERATION_ACK_DATA_FLAGS\": [" << CF_OPERATION_ACK_DATA_FLAG_NONE << "],\n"
              << "    \"CF_OPERATION_ACK_DEHYDRATE_FLAGS\": [" << CF_OPERATION_ACK_DEHYDRATE_FLAG_NONE << "],\n"
              << "    \"CF_OPERATION_ACK_DELETE_FLAGS\": [" << CF_OPERATION_ACK_DELETE_FLAG_NONE << "],\n"
              << "    \"CF_OPERATION_ACK_RENAME_FLAGS\": [" << CF_OPERATION_ACK_RENAME_FLAG_NONE << "],\n"
              << "    \"CF_OPERATION_RESTART_HYDRATION_FLAGS\": [" << CF_OPERATION_RESTART_HYDRATION_FLAG_NONE << ", " << CF_OPERATION_RESTART_HYDRATION_FLAG_MARK_IN_SYNC << "],\n"
              << "    \"CF_OPERATION_RETRIEVE_DATA_FLAGS\": [" << CF_OPERATION_RETRIEVE_DATA_FLAG_NONE << "],\n"
              << "    \"CF_OPERATION_TRANSFER_DATA_FLAGS\": [" << CF_OPERATION_TRANSFER_DATA_FLAG_NONE << "],\n"
              << "    \"CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAGS\": [" << CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_NONE << ", " << CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_STOP_ON_ERROR << ", " << CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_DISABLE_ON_DEMAND_POPULATION << "],\n"
              << "    \"CF_OPERATION_TYPE\": [" << CF_OPERATION_TYPE_TRANSFER_DATA << ", " << CF_OPERATION_TYPE_RETRIEVE_DATA << ", " << CF_OPERATION_TYPE_ACK_DATA << ", " << CF_OPERATION_TYPE_RESTART_HYDRATION << ", " << CF_OPERATION_TYPE_TRANSFER_PLACEHOLDERS << ", " << CF_OPERATION_TYPE_ACK_DEHYDRATE << ", " << CF_OPERATION_TYPE_ACK_DELETE << ", " << CF_OPERATION_TYPE_ACK_RENAME << "],\n"
              << "    \"CF_PIN_STATE\": [" << CF_PIN_STATE_UNSPECIFIED << ", " << CF_PIN_STATE_PINNED << ", " << CF_PIN_STATE_UNPINNED << ", " << CF_PIN_STATE_EXCLUDED << ", " << CF_PIN_STATE_INHERIT << "],\n"
              << "    \"CF_PLACEHOLDER_CREATE_FLAGS\": [" << CF_PLACEHOLDER_CREATE_FLAG_NONE << ", " << CF_PLACEHOLDER_CREATE_FLAG_DISABLE_ON_DEMAND_POPULATION << ", " << CF_PLACEHOLDER_CREATE_FLAG_MARK_IN_SYNC << ", " << CF_PLACEHOLDER_CREATE_FLAG_SUPERSEDE << ", " << CF_PLACEHOLDER_CREATE_FLAG_ALWAYS_FULL << "],\n"
              << "    \"CF_PLACEHOLDER_INFO_CLASS\": [" << CF_PLACEHOLDER_INFO_BASIC << ", " << CF_PLACEHOLDER_INFO_STANDARD << "],\n"
              << "    \"CF_PLACEHOLDER_MANAGEMENT_POLICY\": [" << CF_PLACEHOLDER_MANAGEMENT_POLICY_DEFAULT << ", " << CF_PLACEHOLDER_MANAGEMENT_POLICY_CREATE_UNRESTRICTED << ", " << CF_PLACEHOLDER_MANAGEMENT_POLICY_CONVERT_TO_UNRESTRICTED << ", " << CF_PLACEHOLDER_MANAGEMENT_POLICY_UPDATE_UNRESTRICTED << "],\n"
              << "    \"CF_PLACEHOLDER_RANGE_INFO_CLASS\": [" << CF_PLACEHOLDER_RANGE_INFO_ONDISK << ", " << CF_PLACEHOLDER_RANGE_INFO_VALIDATED << ", " << CF_PLACEHOLDER_RANGE_INFO_MODIFIED << "],\n"
              << "    \"CF_PLACEHOLDER_STATE\": [" << CF_PLACEHOLDER_STATE_NO_STATES << ", " << CF_PLACEHOLDER_STATE_PLACEHOLDER << ", " << CF_PLACEHOLDER_STATE_SYNC_ROOT << ", " << CF_PLACEHOLDER_STATE_ESSENTIAL_PROP_PRESENT << ", " << CF_PLACEHOLDER_STATE_IN_SYNC << ", " << CF_PLACEHOLDER_STATE_PARTIAL << ", " << CF_PLACEHOLDER_STATE_PARTIALLY_ON_DISK << ", " << CF_PLACEHOLDER_STATE_INVALID << "],\n"
              << "    \"CF_POPULATION_POLICY_MODIFIER\": [" << CF_POPULATION_POLICY_MODIFIER_NONE << "],\n"
              << "    \"CF_POPULATION_POLICY_PRIMARY\": [" << CF_POPULATION_POLICY_PARTIAL << ", " << CF_POPULATION_POLICY_FULL << ", " << CF_POPULATION_POLICY_ALWAYS_FULL << "],\n"
              << "    \"CF_REGISTER_FLAGS\": [" << CF_REGISTER_FLAG_NONE << ", " << CF_REGISTER_FLAG_UPDATE << ", " << CF_REGISTER_FLAG_DISABLE_ON_DEMAND_POPULATION_ON_ROOT << ", " << CF_REGISTER_FLAG_MARK_IN_SYNC_ON_ROOT << "],\n"
              << "    \"CF_REVERT_FLAGS\": [" << CF_REVERT_FLAG_NONE << "],\n"
              << "    \"CF_SET_IN_SYNC_FLAGS\": [" << CF_SET_IN_SYNC_FLAG_NONE << "],\n"
              << "    \"CF_SET_PIN_FLAGS\": [" << CF_SET_PIN_FLAG_NONE << ", " << CF_SET_PIN_FLAG_RECURSE << ", " << CF_SET_PIN_FLAG_RECURSE_ONLY << ", " << CF_SET_PIN_FLAG_RECURSE_STOP_ON_ERROR << "],\n"
              << "    \"CF_SYNC_PROVIDER_STATUS\": [" << CF_PROVIDER_STATUS_DISCONNECTED << ", " << CF_PROVIDER_STATUS_IDLE << ", " << CF_PROVIDER_STATUS_POPULATE_NAMESPACE << ", " << CF_PROVIDER_STATUS_POPULATE_METADATA << ", " << CF_PROVIDER_STATUS_POPULATE_CONTENT << ", " << CF_PROVIDER_STATUS_SYNC_INCREMENTAL << ", " << CF_PROVIDER_STATUS_SYNC_FULL << ", " << CF_PROVIDER_STATUS_CONNECTIVITY_LOST << ", " << CF_PROVIDER_STATUS_CLEAR_FLAGS << ", " << CF_PROVIDER_STATUS_TERMINATED << ", " << CF_PROVIDER_STATUS_ERROR << "],\n"
              << "    \"CF_SYNC_ROOT_INFO_CLASS\": [" << CF_SYNC_ROOT_INFO_BASIC << ", " << CF_SYNC_ROOT_INFO_STANDARD << ", " << CF_SYNC_ROOT_INFO_PROVIDER << "],\n"
              << "    \"CF_UPDATE_FLAGS\": [" << CF_UPDATE_FLAG_NONE << ", " << CF_UPDATE_FLAG_VERIFY_IN_SYNC << ", " << CF_UPDATE_FLAG_MARK_IN_SYNC << ", " << CF_UPDATE_FLAG_DEHYDRATE << ", " << CF_UPDATE_FLAG_ENABLE_ON_DEMAND_POPULATION << ", " << CF_UPDATE_FLAG_DISABLE_ON_DEMAND_POPULATION << ", " << CF_UPDATE_FLAG_REMOVE_FILE_IDENTITY << ", " << CF_UPDATE_FLAG_CLEAR_IN_SYNC << ", " << CF_UPDATE_FLAG_REMOVE_PROPERTY << ", " << CF_UPDATE_FLAG_PASSTHROUGH_FS_METADATA << ", " << CF_UPDATE_FLAG_ALWAYS_FULL << ", " << CF_UPDATE_FLAG_ALLOW_PARTIAL << "]\n"
              << "  }\n"
              << "}\n";

    return 0;
}
