#include <windows.h>
#include <winternl.h>
#include <cfapi.h>

#include <cstddef>
#include <iostream>

int main()
{
    constexpr CF_CALLBACK_REGISTRATION callbackRegistrationEnd = CF_CALLBACK_REGISTRATION_END;

    // The probe emits machine-readable ABI facts obtained from the active
    // Windows SDK. Managed tests will compare these values with the bindings.
    std::cout << "{\n"
              << "  \"pointerSize\": " << sizeof(void*) << ",\n"
              << "  \"cfEndOfFile\": " << CF_EOF << ",\n"
              << "  \"cfDefaultRequestKey\": " << CF_REQUEST_KEY_DEFAULT << ",\n"
              << "  \"cfMaxFileIdentityLength\": " << CF_PLACEHOLDER_MAX_FILE_IDENTITY_LENGTH << ",\n"
              << "  \"cfMaxPriorityHint\": " << CF_MAX_PRIORITY_HINT << ",\n"
              << "  \"cfMaxProviderNameLength\": " << CF_MAX_PROVIDER_NAME_LENGTH << ",\n"
              << "  \"cfMaxProviderVersionLength\": " << CF_MAX_PROVIDER_VERSION_LENGTH << ",\n"
              << "  \"cfCallbackRegistrationEndType\": " << callbackRegistrationEnd.Type << ",\n"
              << "  \"cfCallbackRegistrationEndCallbackNull\": " << (callbackRegistrationEnd.Callback == nullptr) << ",\n"
              << "  \"cfPlatformInfoSize\": " << sizeof(CF_PLATFORM_INFO) << ",\n"
              << "  \"cfPlatformInfoBuildNumberOffset\": " << offsetof(CF_PLATFORM_INFO, BuildNumber) << ",\n"
              << "  \"cfPlatformInfoRevisionNumberOffset\": " << offsetof(CF_PLATFORM_INFO, RevisionNumber) << ",\n"
              << "  \"cfPlatformInfoIntegrationNumberOffset\": " << offsetof(CF_PLATFORM_INFO, IntegrationNumber) << ",\n"
              << "  \"cfHydrationPolicySize\": " << sizeof(CF_HYDRATION_POLICY) << ",\n"
              << "  \"cfPopulationPolicySize\": " << sizeof(CF_POPULATION_POLICY) << ",\n"
              << "  \"cfSyncPoliciesSize\": " << sizeof(CF_SYNC_POLICIES) << ",\n"
              << "  \"cfSyncPoliciesHydrationOffset\": " << offsetof(CF_SYNC_POLICIES, Hydration) << ",\n"
              << "  \"cfSyncPoliciesPopulationOffset\": " << offsetof(CF_SYNC_POLICIES, Population) << ",\n"
              << "  \"cfSyncPoliciesInSyncOffset\": " << offsetof(CF_SYNC_POLICIES, InSync) << ",\n"
              << "  \"cfSyncPoliciesHardLinkOffset\": " << offsetof(CF_SYNC_POLICIES, HardLink) << ",\n"
              << "  \"cfSyncPoliciesPlaceholderManagementOffset\": " << offsetof(CF_SYNC_POLICIES, PlaceholderManagement) << ",\n"
              << "  \"cfSyncRegistrationSize\": " << sizeof(CF_SYNC_REGISTRATION) << ",\n"
              << "  \"cfSyncRegistrationProviderNameOffset\": " << offsetof(CF_SYNC_REGISTRATION, ProviderName) << ",\n"
              << "  \"cfSyncRegistrationProviderVersionOffset\": " << offsetof(CF_SYNC_REGISTRATION, ProviderVersion) << ",\n"
              << "  \"cfSyncRegistrationSyncRootIdentityOffset\": " << offsetof(CF_SYNC_REGISTRATION, SyncRootIdentity) << ",\n"
              << "  \"cfSyncRegistrationSyncRootIdentityLengthOffset\": " << offsetof(CF_SYNC_REGISTRATION, SyncRootIdentityLength) << ",\n"
              << "  \"cfSyncRegistrationFileIdentityOffset\": " << offsetof(CF_SYNC_REGISTRATION, FileIdentity) << ",\n"
              << "  \"cfSyncRegistrationFileIdentityLengthOffset\": " << offsetof(CF_SYNC_REGISTRATION, FileIdentityLength) << ",\n"
              << "  \"cfSyncRegistrationProviderIdOffset\": " << offsetof(CF_SYNC_REGISTRATION, ProviderId) << ",\n"
              << "  \"cfSyncRootBasicInfoSize\": " << sizeof(CF_SYNC_ROOT_BASIC_INFO) << ",\n"
              << "  \"cfSyncRootProviderInfoSize\": " << sizeof(CF_SYNC_ROOT_PROVIDER_INFO) << ",\n"
              << "  \"cfSyncRootProviderInfoProviderNameOffset\": " << offsetof(CF_SYNC_ROOT_PROVIDER_INFO, ProviderName) << ",\n"
              << "  \"cfSyncRootProviderInfoProviderVersionOffset\": " << offsetof(CF_SYNC_ROOT_PROVIDER_INFO, ProviderVersion) << ",\n"
              << "  \"cfSyncRootStandardInfoSize\": " << sizeof(CF_SYNC_ROOT_STANDARD_INFO) << ",\n"
              << "  \"cfSyncRootStandardInfoProviderNameOffset\": " << offsetof(CF_SYNC_ROOT_STANDARD_INFO, ProviderName) << ",\n"
              << "  \"cfSyncRootStandardInfoProviderVersionOffset\": " << offsetof(CF_SYNC_ROOT_STANDARD_INFO, ProviderVersion) << ",\n"
              << "  \"cfSyncRootStandardInfoIdentityLengthOffset\": " << offsetof(CF_SYNC_ROOT_STANDARD_INFO, SyncRootIdentityLength) << ",\n"
              << "  \"cfSyncRootStandardInfoIdentityOffset\": " << offsetof(CF_SYNC_ROOT_STANDARD_INFO, SyncRootIdentity) << ",\n"
              << "  \"cfRegisterFlagMarkInSyncOnRoot\": " << CF_REGISTER_FLAG_MARK_IN_SYNC_ON_ROOT << ",\n"
              << "  \"cfHydrationModifierAllowFullRestart\": " << CF_HYDRATION_POLICY_MODIFIER_ALLOW_FULL_RESTART_HYDRATION << ",\n"
              << "  \"cfInSyncPolicyTrackAll\": " << CF_INSYNC_POLICY_TRACK_ALL << ",\n"
              << "  \"cfSyncRootInfoProvider\": " << CF_SYNC_ROOT_INFO_PROVIDER << ",\n"
              << "  \"cfConnectionKeySize\": " << sizeof(CF_CONNECTION_KEY) << ",\n"
              << "  \"cfTransferKeySize\": " << sizeof(CF_TRANSFER_KEY) << ",\n"
              << "  \"cfRequestKeySize\": " << sizeof(CF_REQUEST_KEY) << ",\n"
              << "  \"cfSyncStatusSize\": " << sizeof(CF_SYNC_STATUS) << ",\n"
              << "  \"cfSyncStatusCodeOffset\": " << offsetof(CF_SYNC_STATUS, Code) << ",\n"
              << "  \"cfSyncStatusDescriptionOffsetOffset\": " << offsetof(CF_SYNC_STATUS, DescriptionOffset) << ",\n"
              << "  \"cfSyncStatusDeviceIdOffsetOffset\": " << offsetof(CF_SYNC_STATUS, DeviceIdOffset) << ",\n"
              << "  \"cfProcessInfoSize\": " << sizeof(CF_PROCESS_INFO) << ",\n"
              << "  \"cfCallbackInfoSize\": " << sizeof(CF_CALLBACK_INFO) << ",\n"
              << "  \"cfCallbackInfoConnectionKeyOffset\": " << offsetof(CF_CALLBACK_INFO, ConnectionKey) << ",\n"
              << "  \"cfCallbackInfoCallbackContextOffset\": " << offsetof(CF_CALLBACK_INFO, CallbackContext) << ",\n"
              << "  \"cfCallbackInfoNormalizedPathOffset\": " << offsetof(CF_CALLBACK_INFO, NormalizedPath) << ",\n"
              << "  \"cfCallbackInfoTransferKeyOffset\": " << offsetof(CF_CALLBACK_INFO, TransferKey) << ",\n"
              << "  \"cfCallbackInfoPriorityHintOffset\": " << offsetof(CF_CALLBACK_INFO, PriorityHint) << ",\n"
              << "  \"cfCallbackInfoRequestKeyOffset\": " << offsetof(CF_CALLBACK_INFO, RequestKey) << ",\n"
              << "  \"cfCallbackParametersSize\": " << sizeof(CF_CALLBACK_PARAMETERS) << ",\n"
              << "  \"cfCallbackParametersUnionOffset\": " << offsetof(CF_CALLBACK_PARAMETERS, FetchData) << ",\n"
              << "  \"cfCallbackFetchDataSize\": " << sizeof(((CF_CALLBACK_PARAMETERS*)0)->FetchData) << ",\n"
              << "  \"cfCallbackRegistrationSize\": " << sizeof(CF_CALLBACK_REGISTRATION) << ",\n"
              << "  \"cfCallbackRegistrationCallbackOffset\": " << offsetof(CF_CALLBACK_REGISTRATION, Callback) << ",\n"
              << "  \"cfCallbackTypeNone\": " << CF_CALLBACK_TYPE_NONE << ",\n"
              << "  \"cfConnectFlagBlockSelfImplicitHydration\": " << CF_CONNECT_FLAG_BLOCK_SELF_IMPLICIT_HYDRATION << ",\n"
              << "  \"cfOperationInfoSize\": " << sizeof(CF_OPERATION_INFO) << ",\n"
              << "  \"cfOperationInfoTransferKeyOffset\": " << offsetof(CF_OPERATION_INFO, TransferKey) << ",\n"
              << "  \"cfOperationInfoRequestKeyOffset\": " << offsetof(CF_OPERATION_INFO, RequestKey) << ",\n"
              << "  \"cfOperationParametersSize\": " << sizeof(CF_OPERATION_PARAMETERS) << ",\n"
              << "  \"cfOperationParametersUnionOffset\": " << offsetof(CF_OPERATION_PARAMETERS, TransferData) << ",\n"
              << "  \"cfOperationTransferDataSize\": " << sizeof(((CF_OPERATION_PARAMETERS*)0)->TransferData) << ",\n"
              << "  \"cfFsMetadataSize\": " << sizeof(CF_FS_METADATA) << ",\n"
              << "  \"cfPlaceholderCreateInfoSize\": " << sizeof(CF_PLACEHOLDER_CREATE_INFO) << ",\n"
              << "  \"cfPlaceholderCreateInfoMetadataOffset\": " << offsetof(CF_PLACEHOLDER_CREATE_INFO, FsMetadata) << ",\n"
              << "  \"cfPlaceholderCreateInfoCreateUsnOffset\": " << offsetof(CF_PLACEHOLDER_CREATE_INFO, CreateUsn) << ",\n"
              << "  \"cfPlaceholderCreateFlagAlwaysFull\": " << CF_PLACEHOLDER_CREATE_FLAG_ALWAYS_FULL << ",\n"
              << "  \"cfFileRangeSize\": " << sizeof(CF_FILE_RANGE) << ",\n"
              << "  \"cfFileRangeStartingOffsetOffset\": " << offsetof(CF_FILE_RANGE, StartingOffset) << ",\n"
              << "  \"cfFileRangeLengthOffset\": " << offsetof(CF_FILE_RANGE, Length) << ",\n"
              << "  \"cfConvertFlagForceConvertToCloudFile\": " << CF_CONVERT_FLAG_FORCE_CONVERT_TO_CLOUD_FILE << ",\n"
              << "  \"cfUpdateFlagAllowPartial\": " << CF_UPDATE_FLAG_ALLOW_PARTIAL << ",\n"
              << "  \"cfDehydrateFlagBackground\": " << CF_DEHYDRATE_FLAG_BACKGROUND << ",\n"
              << "  \"cfPinStateInherit\": " << CF_PIN_STATE_INHERIT << ",\n"
              << "  \"cfSetPinFlagRecurseStopOnError\": " << CF_SET_PIN_FLAG_RECURSE_STOP_ON_ERROR << ",\n"
              << "  \"cfInSyncStateInSync\": " << CF_IN_SYNC_STATE_IN_SYNC << ",\n"
              << "  \"cfPlaceholderBasicInfoSize\": " << sizeof(CF_PLACEHOLDER_BASIC_INFO) << ",\n"
              << "  \"cfPlaceholderBasicInfoIdentityOffset\": " << offsetof(CF_PLACEHOLDER_BASIC_INFO, FileIdentity) << ",\n"
              << "  \"cfPlaceholderStandardInfoSize\": " << sizeof(CF_PLACEHOLDER_STANDARD_INFO) << ",\n"
              << "  \"cfPlaceholderStandardInfoIdentityOffset\": " << offsetof(CF_PLACEHOLDER_STANDARD_INFO, FileIdentity) << ",\n"
              << "  \"cfCorrelationVectorSize\": " << sizeof(CORRELATION_VECTOR) << ",\n"
              << "  \"cfCorrelationVectorValueOffset\": " << offsetof(CORRELATION_VECTOR, Vector) << ",\n"
              << "  \"win32FindDataWSize\": " << sizeof(WIN32_FIND_DATAW) << ",\n"
              << "  \"win32FindDataWReparseTagOffset\": " << offsetof(WIN32_FIND_DATAW, dwReserved0) << ",\n"
              << "  \"win32FindDataWFileNameOffset\": " << offsetof(WIN32_FIND_DATAW, cFileName) << ",\n"
              << "  \"cfPlaceholderInfoClassStandard\": " << CF_PLACEHOLDER_INFO_STANDARD << ",\n"
              << "  \"cfPlaceholderRangeInfoModified\": " << CF_PLACEHOLDER_RANGE_INFO_MODIFIED << ",\n"
              << "  \"cfPlaceholderStatePartiallyOnDisk\": " << CF_PLACEHOLDER_STATE_PARTIALLY_ON_DISK << "\n"
              << "}\n";

    return 0;
}
